### PR TITLE
limits file watcher supports k8s envs

### PR DESCRIPTION
**Pull request by eguzki**
#### what

Currently, the limits file watcher reloads limits when there is a file change on local and dockerized environments when the file is mounted from host local filesystem. However, when the limits file source is a populated volume with data stored in a k8s configmap, the watcher does not reload limits when the content is changed. 

This PR adds support to limits stored in k8s config map and reloads limits when the configmap's limits change.

Additionally, End2End integration test implemented. It is called `Limits File Watcher in k8s environment`

#### why 
Unfortunately (or fortunately), things in k8s env are not what they look like. When k8s (kubelet agent) populates a volume with data stored in a ConfigMap, the resulting file is a symbolic link. And when there is a configmap replacement, the file is not "simply" updated. In few words, it is moved. 

With the current configuration, the inotify watcher was totally unaware of the configmap replacements.

```rust
 let mut watcher = RecommendedWatcher::new(move |result: Result<Event, Error>| match result {      
         Ok(ref event) => {                                                          
             if let EventKind::Modify(ModifyKind::Data(_)) = event.kind { ... }                                                                
         }                                                                                                                              
 })?;                                                                                                                                                          
 watcher.watch(Path::new(&limits_file_path), RecursiveMode::Recursive)?;             
```
The `EventHandler` implemented with the closure never gets called. It's not an issue with the filtering of the event. The event simply did not happen. 

What does a volume populated with data stored in a configmap look like? It is the result of a double symlink indirection

```
/home/limitador/bin $ ls -al /home/limitador/etc                                                     
total 0                                                                                              
drwxrwsrwx    3 root     10007600       100 Jul 20 22:25 .                                           
drwxr-sr-x    1 limitado limitado        17 Jul 20 22:25 ..                                          
drwxr-sr-x    2 root     10007600        47 Jul 20 22:25 ..2022_07_20_22_25_07.358335008             
lrwxrwxrwx    1 root     10007600        31 Jul 20 22:25 ..data -> ..2022_07_20_22_25_07.358335008                    
lrwxrwxrwx    1 root     10007600        28 Jul 20 22:25 limitador-config.yaml -> ..data/limitador-config.yaml
```

And what happens when there is a configmap replacement? A new directory is created, new file is created in it with the new content of the configmap. Then, k8s updates the `..data` , removing the existing symlink and creating a new one targeting the newly created directory. Then removes the old base directory with the old data file. After a configmap replacement, the resulting `/home/limitador/etc` folder looks like this:

```
/home/limitador/bin $ ls -al /home/limitador/etc                                                     
total 0                                                                                              
drwxrwsrwx    3 root     10007600       100 Jul 20 22:32 .                                           
drwxr-sr-x    1 limitado limitado        17 Jul 20 22:25 ..                                          
drwxr-sr-x    2 root     10007600        47 Jul 20 22:32 ..2022_07_20_22_32_00.023471129             
lrwxrwxrwx    1 root     10007600        31 Jul 20 22:32 ..data -> ..2022_07_20_22_32_00.023471129                        
lrwxrwxrwx    1 root     10007600        28 Jul 20 22:25 limitador-config.yaml -> ..data/limitador-config.yaml
```

Note that `/home/limitador/etc/limitador-config.yaml` symlink targets the new content and effectively has changed the content. However, only because the underlying symlink pointers have changed. There was not a real OS file content "Write" operation. The operation would be something like this

```bash
ln -sfn ..2022_07_20_22_32_00.023471129 data
```

Logging events generated when actually the content of a file has changed
<details>

```
2022-07-21T15:18:15Z INFO  limitador_server] Event!!! Event { kind: Modify(Data(Any)), paths: ["/home/eguzki/testing/1/limits.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T15:18:15Z INFO  limitador_server] Event!!! Event { kind: Modify(Metadata(Any)), paths: ["/home/eguzki/testing/1/limits.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T15:18:15Z INFO  limitador_server] Event!!! Event { kind: Access(Close(Write)), paths: ["/home/eguzki/testing/1/limits.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```

</details>

Logging events generated when imitating k8s behavior locally with `ln -sfn ..2022_07_20_22_32_00.023471129 data'' (watching the parent directory instead of the file)
<details>

```
2022-07-21T16:35:35Z INFO  limitador_server] Event!!! Event { kind: Create(File), paths: ["/home/eguzki/testing/CuRqFcEx"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T16:35:35Z INFO  limitador_server] Event!!! Event { kind: Modify(Name(From)), paths: ["/home/eguzki/testing/CuRqFcEx"], attr:tracker: Some(13913), attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T16:35:35Z INFO  limitador_server] Event!!! Event { kind: Modify(Name(To)), paths: ["/home/eguzki/testing/data"], attr:tracker: Some(13913), attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T16:35:35Z INFO  limitador_server] Event!!! Event { kind: Modify(Name(Both)), paths: ["/home/eguzki/testing/CuRqFcEx", "/home/eguzki/testing/data"], attr:tracker: Some(13913), attr:flag: None, attr:info: None, attr:source: None }
```

</details>

Logging events generated when in k8s when there is a configmap replacement (watching the parent directory instead of the file)
<details>

```
[2022-07-21T22:43:27Z INFO  limitador_server] Event!!! Event { kind: Create(Folder), paths: ["/home/limitador/etc/..2022_07_21_22_43_27.287303002"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T22:43:27Z INFO  limitador_server] Event!!! Event { kind: Modify(Metadata(Any)), paths: ["/home/limitador/etc/..2022_07_21_22_43_27.287303002"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T22:43:27Z INFO  limitador_server] Event!!! Event { kind: Create(File), paths: ["/home/limitador/etc/..data_tmp"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T22:43:27Z INFO  limitador_server] Event!!! Event { kind: Modify(Name(From)), paths: ["/home/limitador/etc/..data_tmp"], attr:tracker: Some(4021), attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T22:43:27Z INFO  limitador_server] Event!!! Event { kind: Modify(Name(To)), paths: ["/home/limitador/etc/..data"], attr:tracker: Some(4021), attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T22:43:27Z INFO  limitador_server] Event!!! Event { kind: Modify(Name(Both)), paths: ["/home/limitador/etc/..data_tmp", "/home/limitador/etc/..data"], attr:tracker: Some(4021), attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T22:43:27Z INFO  limitador_server] Event!!! Event { kind: Remove(File), paths: ["/home/limitador/etc/..data/hash"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T22:43:27Z INFO  limitador_server] Event!!! Event { kind: Remove(File), paths: ["/home/limitador/etc/..data/limitador-config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
[2022-07-21T22:43:27Z INFO  limitador_server] Event!!! Event { kind: Remove(Folder), paths: ["/home/limitador/etc/..2022_07_21_22_36_55.967227880"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```

</details>

#### how

Basic ideas "taken" from [Kubernetes ConfigMap hot-reload in action with Viper](https://medium.com/@xcoulon/kubernetes-configmap-hot-reload-in-action-with-viper-d413128a1c9a) and linked [PR](https://github.com/spf13/viper/pull/415) to support "watchConfig" in k8s.

First relevant change: watch the parent directory instead of the limits file. This will enable reading events.

Then, limits will be reloaded when either of the following happens
* actual limits file content has been changed
* Keep state of the last known real (no symlinks) limits file path and the limits real file path has changed. 

An enhancement for the second case would be to use the hash and only reload limits when the hash changes.

This implementation should cover Limitador running in both bare metal and k8s envs.

#### verification steps locally

Create first limits file path dir `limitDir1` under some path (in my case `/home/eguzki/testing`)
```
mkdir /home/eguzki/testing/limitDir1
```

Add content to the first limits file

```yaml
cat <<EOF >/home/eguzki/testing/limitDir1/limits.yaml
---
- namespace: test_namespace
  max_value: 20
  seconds: 60
  conditions:
    - "req.method == GET"
  variables:
    - user_id
EOF
```
First directory symlink
```bash
cd /home/eguzki/testing
ln -s limitDir1 data
```
Second file symlink
```bash
cd /home/eguzki/testing
ln -s data/limits.yaml limits.yaml
```
Run limitador with `LIMITS_FILE=/home/eguzki/testing/limits.yaml`. Note that no `limitDir1` or `data` references.
```
RUST_LOG=debug LIMITS_FILE=/home/eguzki/testing/limits.yaml cargo run
```
Read limits from admin HTTP endpoint
```
curl http://127.0.0.1:8080/limits/test_namespace 2>/dev/null | yq e -P 
- namespace: test_namespace
  max_value: 20
  seconds: 60
  name: null
  conditions:
    - req.method == GET
  variables:
    - user_id
```
Create a second configuration in `limitDir2`. Limitador must be up&running.

```
mkdir /home/eguzki/testing/limitDir2
```

Add content to the second limits file. Same as the first limits file, but limit's condition changes to `POST`.

```yaml
cat <<EOF >/home/eguzki/testing/limitDir2/limits.yaml
---
- namespace: test_namespace
  max_value: 20
  seconds: 60
  conditions:
    - "req.method == POST"
  variables:
    - user_id
EOF
```
Update `data` symlink to target second limit file
```bash
cd /home/eguzki/testing
ln -sfn limitDir2 data
```
Verify limits have been reloaded reading the admin HTTP endpoint
```
curl http://127.0.0.1:8080/limits/test_namespace 2>/dev/null | yq e -P 
- namespace: test_namespace
  max_value: 20
  seconds: 60
  name: null
  conditions:
    - req.method == POST
  variables:
    - user_id
```

#### verification steps in k8s

We will be using Limitador Operator to easily manage limits from the Limitador CR.

First, push limitador image with the current PR changes
```
docker build -t quay.io/3scale/limitador:support-k8s .
docker push quay.io/3scale/limitador:support-k8s
```
Clone limitador operator and run local k8s env
```
git clone https://github.com/Kuadrant/limitador-operator.git
cd limitador-operator
make local-setup
```
Deploy limitador with our custom image one and one limit configured
```yaml
k apply -f - <<EOF
apiVersion: limitador.kuadrant.io/v1alpha1
kind: Limitador
metadata:
  name: limitador-sample
spec:
  replicas: 1
  version: support-k8s
  listener:
    http:
      port: 8080
    grpc:
      port: 8081
  limits:
    - conditions: ["get-toy == yes"]
      max_value: 2
      namespace: toystore-app
      seconds: 30
      variables: []
EOF
```
When up&running, read limits from admin HTTP endpoint
```
kubectl port-forward deployment/limitador-sample 8080
```
```yaml
curl http://127.0.0.1:8080/limits/toystore-app 2>/dev/null | yq e -P 
- namespace: toystore-app
  max_value: 2
  seconds: 30
  name: null
  conditions:
    - get-toy == yes
  variables: []
```
Modify limits from the Limit CR. This will trigger a change in the configmap, which in turn will trigger change in mounted path of the limitador's deployment. The change is simple, just update limit's `seconds` to `60`.
```
k patch limitador limitador-sample --type json --patch='[{"op": "replace", "path": "/spec/limits/0/seconds", "value": 60}]'
```

Wait few secs, eventually, the admin HTTP endpoint should return the new limit verifying it has been reloaded. 

```yaml
curl http://127.0.0.1:8080/limits/toystore-app 2>/dev/null | yq e -P 
- namespace: toystore-app
  max_value: 2
  seconds: 60
  name: null
  conditions:
    - get-toy == yes
  variables: []
```

### CODE REVIEW

**Comment by eguzki** [comment]
@alexsnaps note that this is a draft PR. I left some logging statements that I can remove later.

I would like to improve some implementation details being more idiomatic with rust. For example, it feels to me that the `LimitsPath` struct is not needed at all.

I would like to implement some testing. However, the watcher implementation is in the `main.rs` and hence hard to test. Looking for guidance here. I was thinking in moving the watcher implementation to another module and test it. 

Can you run some tests in OSX to ensure it still works there?

**Comment by alexsnaps** [comment]
@eguzki if you don't get to this anymore, I'll take over this PR next week… no worries!

**Comment by eguzki** [comment]
I will resolve conflicts and see why e2e tests are failing after doing, apparently, cosmetic changes in https://github.com/Kuadrant/limitador/pull/95/commits/555ef26ec5ae658f436d56885ad53e86a49091fa

**Comment by alexsnaps** [comment]
Merged as part of #98

**Pull request closed without merging**
