### PR TITLE
bump alpine image

### PR DESCRIPTION
**Pull request by MStokluska**

### CODE REVIEW

**Review by eguzki — APPROVED** [review]

**Comment by unleashed** [comment]
#58 does this along fixing thr build with 3.15. We should probably update that PR.

**Comment by MStokluska** [comment]
> #58 does this along fixing the build with 3.15. We should probably update that PR.

@unleashed just noticed your previous PR too, would it make sense to bump alpine to 3.16 instead of 3.15?

**Comment by unleashed** [comment]
> > #58 does this along fixing the build with 3.15. We should probably update that PR.
> 
> @unleashed just noticed your previous PR too, would it make sense to bump alpine to 3.16 instead of 3.15?

Definitely.

**Comment by eguzki** [comment]
merged #58, please rebase and update both builder and runtime image

**Pull request merged**
